name: tests

on: 
  push:
      branches:
          - main

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    env:
      matlib: 1.1.0
      testlib: 0.0.14
      repository: ${{ github.actor }}/rindow-matlib

    strategy:
      #fail-fast: true
      matrix:
        include:
          - name: Windows
            os: windows-latest
            php: '8.3'

#          - name: PHP8.1
#            os: ubuntu-latest
#            php: '8.1'
#          - name: PHP8.2
#            os: ubuntu-latest
#            php: '8.2'
#          - name: PHP8.3
#            os: ubuntu-latest
#            php: '8.3'
#          - name: macOS-arm64
#            os: macos-latest
#            php: '8.3'
#          - name: macOS-x86_64
#            os: macos-13
#            php: '8.3'

  
    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpunit:10.5, phpstan
          #ini-values: "memory_limit=512M"
          extensions: ffi

      - name: Setup Matlib (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: |
          wget https://github.com/${repository}/releases/download/${testlib}/rindow-matlib_${matlib}_amd64.deb
          sudo apt install -y ./rindow-matlib_${matlib}_amd64.deb

        #    sudo update-alternatives --set librindowmatlib.so /usr/lib/rindowmatlib-serial/librindowmatlib.so

      - name: Checkout codes
        uses: "actions/checkout@v4"

      #- name: Composer
      #  uses: php-actions/composer@v6
      #  with:
      #    php_version: ${{ matrix.php }}
      #    php_extensions: ffi

      - name: Composer
        run: |
          composer update

      #- name: PHP Static Analysys
      #  uses: php-actions/phpstan@v3
      #  with:
      #    php_version: ${{ matrix.php }}
      #    path: src/

      - name: PHP Static Analysys
        run: phpstan

      #- name: PHPUnit Tests
      #  uses: php-actions/phpunit@v3
      #  with:
      #    configuration: tests/phpunit.xml
      #    version: 10.5
      #    php_version: ${{ matrix.php }}
      #    #php_extensions: ffi
      #    filter: ReleaseTest

      - name: PHPUnit Tests
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: | 
          phpunit -c tests

      - name: PHPUnit Tests (macOS)
        if: ${{ startsWith(matrix.os, 'macos-latest') }}
        run: |
          brew install libomp
          curl https://github.com/${{ env.repository }}/releases/download/${{ env.testlib }}/rindow-matlib-${{ env.matlib }}-Darwin-arm64.tar.gz -O -L
          tar -xzf rindow-matlib-${{ env.matlib }}-Darwin-arm64.tar.gz
          sudo cp -r usr/include /usr/local/
          sudo cp -r usr/lib /usr/local/
          phpunit -c tests

      - name: PHPUnit Tests (macOS)
        if: ${{ startsWith(matrix.os, 'macos-13') }}
        run: |
          brew install libomp
          curl https://github.com/${{ env.repository }}/releases/download/${{ env.testlib }}/rindow-matlib-${{ env.matlib }}-Darwin-x86_64.tar.gz -O -L
          tar -xzf rindow-matlib-${{ env.matlib }}-Darwin-x86_64.tar.gz
          sudo cp -r usr/include /usr/local/
          sudo cp -r usr/lib /usr/local/
          phpunit -c tests

      - name: PHPUnit Tests (Windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}
        run: | 
          Invoke-WebRequest -Uri https://github.com/${{ env.repository }}/releases/download/${{ env.testlib }}/rindow-matlib-${{ env.matlib }}-win64.zip -OutFile matlib.zip
          Expand-Archive -Path matlib.zip
          $currentDir = (Get-Location).Path
          $matlibDir = Join-Path -Path $currentDir -ChildPath 'matlib\bin'
          $env:PATH = "$matlibDir;$env:PATH"
          phpunit -c tests --filter MatlibTest::testaddSameSizeNormal
